import requests
import os
from datetime import datetime

def fetch_jobs():
    """Fetch jobs from RemoteOK API (free, no auth needed)"""
    
    url = "https://remoteok.com/api"
    
    try:
        response = requests.get(url)
        data = response.json()
        
        jobs = []
        for job in data[1:30]:  # Skip first item (it's metadata), get next 30
            # Filter for async/remote keywords
            if any(keyword in str(job).lower() for keyword in ["async", "remote", "distributed"]):
                jobs.append({
                    "title": job.get("title", "N/A"),
                    "company": job.get("company", "N/A"),
                    "location": job.get("location", "Remote"),
                    "salary": job.get("salary", "Competitive"),
                    "description": job.get("description", "")[:250],
                    "link": job.get("url", "#")
                })
        
        return jobs[:15]  # Return top 15
        
    except Exception as e:
        print(f"Error fetching jobs: {e}")
        return []

def send_email_sendgrid(jobs):
    """Send via SendGrid"""
    
    api_key = os.getenv("SENDGRID_API_KEY")
    
    html = f"""
    <html>
        <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
            <h2 style="color: #2c3e50;">📧 Today's Remote Jobs</h2>
            <p>Found <strong>{len(jobs)}</strong> async remote opportunities.</p>
    """
    
    if jobs:
        html += "<ul style='list-style: none; padding: 0;'>"
        for i, job in enumerate(jobs, 1):
            html += f"""
            <li style="margin-bottom: 20px; padding: 15px; background: #f8f9fa; border-left: 4px solid #3498db; border-radius: 4px;">
                <strong style="font-size: 16px;">#{i} {job['title']}</strong><br>
                <span style="color: #7f8c8d;"><strong>{job['company']}</strong> • {job['location']}</span><br>
                <span style="color: #27ae60; font-weight: bold;">{job['salary']}</span><br>
                <p style="margin: 10px 0; font-size: 14px;">{job['description']}...</p>
                <a href="{job['link']}" style="display: inline-block; padding: 8px 16px; background: #3498db; color: white; text-decoration: none; border-radius: 4px;">View Job →</a>
            </li>
            """
        html += "</ul>"
    else:
        html += "<p>No jobs found today.</p>"
    
    html += """
            <hr style="margin-top: 30px; border: none; border-top: 1px solid #ddd;">
            <p style="font-size: 12px; color: #95a5a6;">
                Auto-generated by GitHub Actions
            </p>
        </body>
    </html>
    """
    
    url = "https://api.sendgrid.com/v3/mail/send"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }
    
    data = {
        "personalizations": [
            {
                "to": [{"email": "maria.galyean.work@gmail.com"}]
            }
        ],
        "from": {"email": "maria@thehomeschooladmin.com", "name": "Job Alert Bot"},
        "subject": f"🎯 Remote Jobs - {datetime.now().strftime('%B %d, %Y')}",
        "content": [
            {
                "type": "text/html",
                "value": html
            }
        ]
    }
    
    response = requests.post(url, json=data, headers=headers)
    
    if response.status_code == 202:
        print(f"✅ Email sent! {len(jobs)} jobs included")
    else:
        print(f"❌ Error: {response.status_code} - {response.text}")

if __name__ == "__main__":
    jobs = fetch_jobs()
    send_email_sendgrid(jobs)
